-- 智愈业务库 schema（PostgreSQL 16），镜像既有 Python 模型，勿改列名语义
-- 主键用 BY DEFAULT IDENTITY，保证幂等 seed 可写显式 id
-- 开发期 schema 演进约定：drop + recreate + seed，不做隐式迁移

CREATE TABLE IF NOT EXISTS hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    level VARCHAR(30),
    address VARCHAR(255),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    name VARCHAR(100),
    floor VARCHAR(30),
    location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(id),
    name VARCHAR(50),
    title VARCHAR(50),
    specialty TEXT,
    photo_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL REFERENCES doctors(id),
    schedule_date DATE NOT NULL,
    time_slot VARCHAR(30) NOT NULL,
    total_slots INT NOT NULL,
    remaining_slots INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_schedules_total_slots_positive CHECK (total_slots > 0),
    CONSTRAINT ck_schedules_remaining_slots_range CHECK (remaining_slots >= 0 AND remaining_slots <= total_slots)
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    role VARCHAR(20),
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    title VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_active_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS report_interpretations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    request_id VARCHAR(64) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    page_count INT,
    status VARCHAR(20) NOT NULL,
    result_json TEXT,
    context_summary TEXT,
    error_code VARCHAR(50),
    disclaimer VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_report_interpretations_request UNIQUE (patient_id, request_id),
    CONSTRAINT ck_report_interpretations_status
        CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    kind VARCHAR(20) NOT NULL DEFAULT 'text',
    content TEXT NOT NULL,
    effort VARCHAR(10),
    report_interpretation_id BIGINT REFERENCES report_interpretations(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    schedule_id BIGINT NOT NULL REFERENCES schedules(id),
    sequence_number INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'BOOKED',
    condition_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cancelled_at TIMESTAMPTZ,
    CONSTRAINT uq_appointments_patient_schedule UNIQUE (patient_id, schedule_id),
    CONSTRAINT uq_appointments_schedule_sequence UNIQUE (schedule_id, sequence_number),
    CONSTRAINT ck_appointments_status CHECK (status IN ('BOOKED', 'CANCELLED', 'VISITED'))
);

CREATE TABLE IF NOT EXISTS consultation_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id),
    doctor_id BIGINT NOT NULL REFERENCES doctors(id),
    diagnosis TEXT NOT NULL,
    advice TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    generic_name VARCHAR(100) NOT NULL,
    specification VARCHAR(100) NOT NULL,
    instructions TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id),
    doctor_id BIGINT NOT NULL REFERENCES doctors(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    review_reason TEXT,
    reviewed_by BIGINT REFERENCES staff_users(id),
    interpretation TEXT,
    disclaimer VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT ck_prescriptions_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_prescriptions_patient_visibility CHECK (
        (status = 'APPROVED' AND interpretation IS NOT NULL AND disclaimer IS NOT NULL)
        OR status <> 'APPROVED'
    )
);

CREATE TABLE IF NOT EXISTS prescription_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
    medication_id BIGINT NOT NULL REFERENCES medications(id),
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    notes VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS in_app_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    type VARCHAR(40) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    disclaimer VARCHAR(100) NOT NULL,
    related_appointment_id BIGINT REFERENCES appointments(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_in_app_messages_appointment_type UNIQUE (related_appointment_id, type)
);

CREATE INDEX IF NOT EXISTS idx_conversations_patient ON conversations(patient_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_report_interpretations_patient
    ON report_interpretations(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_consultation_records_doctor ON consultation_records(doctor_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_status ON prescriptions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_in_app_messages_patient ON in_app_messages(patient_id, created_at DESC);
