-- 智愈业务库 schema（PostgreSQL 16），镜像既有 Python 模型，勿改列名语义
-- 主键用 BY DEFAULT IDENTITY，保证幂等 seed 可写显式 id
-- 开发期 schema 演进约定：drop + recreate + seed，不做隐式迁移

-- pgvector 扩展：knowledge_chunks 向量检索依赖（云库 init.sql 已装，此处兜底防裸库）
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    level VARCHAR(30),
    address VARCHAR(255),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    -- 就诊指引卡静态来源（票 43）：地址错误后果重，演示用虚构医院静态值，非 LLM 生成
    floor VARCHAR(30),
    materials TEXT,
    precautions TEXT
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    name VARCHAR(100),
    floor VARCHAR(30),
    location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(id),
    name VARCHAR(50),
    title VARCHAR(50),
    registration_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
    specialty TEXT,
    photo_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL REFERENCES doctors(id),
    schedule_date DATE NOT NULL,
    time_slot VARCHAR(30) NOT NULL,
    total_slots INT NOT NULL,
    remaining_slots INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_schedules_total_slots_positive CHECK (total_slots > 0),
    CONSTRAINT ck_schedules_remaining_slots_range CHECK (remaining_slots >= 0 AND remaining_slots <= total_slots)
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    role VARCHAR(20),
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    title VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_active_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS health_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    display_name VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    birth_date DATE NOT NULL,
    relationship VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_health_profiles_active_patient
    ON health_profiles(patient_id) WHERE active = TRUE;

CREATE TABLE IF NOT EXISTS health_profile_allergies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    health_profile_id BIGINT NOT NULL REFERENCES health_profiles(id) ON DELETE CASCADE,
    allergen VARCHAR(100) NOT NULL,
    CONSTRAINT uq_health_profile_allergen UNIQUE (health_profile_id, allergen)
);

CREATE TABLE IF NOT EXISTS report_interpretations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    health_profile_id BIGINT NOT NULL REFERENCES health_profiles(id),
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    request_id VARCHAR(64) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    page_count INT,
    status VARCHAR(20) NOT NULL,
    result_json TEXT,
    context_summary TEXT,
    error_code VARCHAR(50),
    disclaimer VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_report_interpretations_request UNIQUE (patient_id, request_id),
    CONSTRAINT ck_report_interpretations_status
        CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    -- 须容纳契约 message_kinds 最长值（hospital_recommendations=24）并留余量；
    -- 票 33：VARCHAR(20) 溢出曾使卡片落库失败并掐断 SSE 中继，列宽由 ContractsConsistencyTest 钉死
    kind VARCHAR(32) NOT NULL DEFAULT 'text',
    content TEXT NOT NULL,
    effort VARCHAR(10),
    report_interpretation_id BIGINT REFERENCES report_interpretations(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    request_id VARCHAR(64) NOT NULL,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    assistant_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(50),
    accepted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_chat_rounds_patient_request UNIQUE (patient_id, request_id),
    CONSTRAINT ck_chat_rounds_status CHECK (status IN ('ACCEPTED', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    health_profile_id BIGINT NOT NULL REFERENCES health_profiles(id),
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    schedule_id BIGINT NOT NULL REFERENCES schedules(id),
    sequence_number INT NOT NULL,
    registration_fee DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'BOOKED',
    condition_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cancelled_at TIMESTAMPTZ,
    CONSTRAINT uq_appointments_profile_schedule UNIQUE (health_profile_id, schedule_id),
    CONSTRAINT uq_appointments_schedule_sequence UNIQUE (schedule_id, sequence_number),
    CONSTRAINT ck_appointments_status CHECK (status IN ('BOOKED', 'CANCELLED', 'VISITED'))
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id),
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at TIMESTAMPTZ,
    CONSTRAINT ck_payments_status CHECK (status IN ('UNPAID', 'PAID'))
);

CREATE TABLE IF NOT EXISTS consultation_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id),
    doctor_id BIGINT NOT NULL REFERENCES doctors(id),
    diagnosis TEXT NOT NULL,
    advice TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    generic_name VARCHAR(100) NOT NULL,
    specification VARCHAR(100) NOT NULL,
    instructions TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 知识库分块：一场景一 chunk，向量列维度写死 2048（路径 B，ADR-0010）。
-- 维度实际值连 endpoint 探测确认（doubao-embedding-vision 返回 2048）。
-- department 衔接导诊科室推荐；向量由离线 embedding 工具产出的 seed-knowledge.sql 回填，
-- 运行时 server-py 对本表只读检索（embed query + Top-K + 阈值过滤）。
CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    vector vector(2048),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 知识库向量索引：doubao-embedding-vision 返回 2048 维，超过 pgvector HNSW 的 2000 维
-- 上限。知识库规模小（50 场景），用顺序扫描 + cosine 距离排序即可，不建近似索引。
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_department ON knowledge_chunks(department);

CREATE TABLE IF NOT EXISTS prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id),
    doctor_id BIGINT NOT NULL REFERENCES doctors(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    review_reason TEXT,
    reviewed_by BIGINT REFERENCES staff_users(id),
    interpretation TEXT,
    disclaimer VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT ck_prescriptions_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_prescriptions_patient_visibility CHECK (
        (status = 'APPROVED' AND interpretation IS NOT NULL AND disclaimer IS NOT NULL)
        OR status <> 'APPROVED'
    )
);

CREATE TABLE IF NOT EXISTS prescription_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
    medication_id BIGINT NOT NULL REFERENCES medications(id),
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    notes VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS drug_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    prescription_id BIGINT NOT NULL REFERENCES prescriptions(id),
    status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    total_amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    CONSTRAINT ck_drug_orders_status CHECK (status IN ('UNPAID', 'PAID', 'DONE', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS drug_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_order_id BIGINT NOT NULL REFERENCES drug_orders(id) ON DELETE CASCADE,
    medication_id BIGINT NOT NULL REFERENCES medications(id),
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    CONSTRAINT ck_drug_order_items_quantity_positive CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS in_app_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    type VARCHAR(40) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    disclaimer VARCHAR(100) NOT NULL,
    related_appointment_id BIGINT REFERENCES appointments(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_in_app_messages_appointment_type UNIQUE (related_appointment_id, type)
);

-- Agent 调用日志（票 24）：每条工具进度事件一行，tool_start/tool_end 用 tool_call_id 配对。
-- 字段为白名单，**无任何原文列**（不存工具参数与返回体，硬约束 5：trace 不记录患者敏感原文）。
-- 不存在的列无法被误写，运行时无需脱敏逻辑（ADR-0018）。error_code 只存契约白名单码，
-- 非白名单统一记 TOOL_ERROR_UNKNOWN（复用 vision-errors.json 同款纪律）。
CREATE TABLE IF NOT EXISTS agent_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES chat_rounds(id) ON DELETE CASCADE,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    -- LangGraph 工具调用 ID：作为 tool_start/tool_end 配对键透传
    tool_call_id VARCHAR(64),
    tool_name VARCHAR(50) NOT NULL,
    -- 阶段：tool_start / tool_end
    phase VARCHAR(20) NOT NULL,
    -- tool_end 结果枚举：success/error/skipped；tool_start 时为 NULL
    result VARCHAR(20),
    -- duration_ms 由 server-java 按 tool_start->tool_end 墙钟计算（server-py 不背时钟）
    duration_ms INT,
    -- 只存契约白名单码；非白名单统一记 TOOL_ERROR_UNKNOWN
    error_code VARCHAR(50),
    -- 同一轮内的事件序号，B 端按 round_id + seq 还原顺序
    seq INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_agent_call_logs_phase CHECK (phase IN ('tool_start', 'tool_end')),
    CONSTRAINT ck_agent_call_logs_result CHECK (result IS NULL OR result IN ('success', 'error', 'skipped'))
);

-- 服药打卡生命周期表：处方审核通过时 eager 预生成每日一条 PENDING，到点打卡推进 CHECKED（ADR-0018）。
-- 不复用 in_app_messages：该表是 append-only 事件表，而打卡记录是带 due_date/status 的状态机记录，
-- 两者只共用 C 端消息页 UI（站内消息通道），物理分离、各守各的约束。
CREATE TABLE IF NOT EXISTS med_checkin_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    health_profile_id BIGINT NOT NULL REFERENCES health_profiles(id),
    prescription_id BIGINT NOT NULL REFERENCES prescriptions(id),
    prescription_item_id BIGINT NOT NULL REFERENCES prescription_items(id),
    medication_name VARCHAR(100) NOT NULL,
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    checked_at TIMESTAMPTZ,
    disclaimer VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 生成幂等：同一处方明细同一提醒日只允许一条，重复审核/重投静默吞掉（ON CONFLICT DO NOTHING）。
    CONSTRAINT uq_med_checkin_item_date UNIQUE (prescription_item_id, due_date),
    CONSTRAINT ck_med_checkin_status CHECK (status IN ('PENDING', 'CHECKED')),
    -- CHECKED 必须有打卡时间；PENDING 不得有打卡时间，状态机一致性兜底。
    CONSTRAINT ck_med_checkin_checked_at
        CHECK ((status = 'CHECKED' AND checked_at IS NOT NULL)
            OR (status = 'PENDING' AND checked_at IS NULL))
);

CREATE INDEX IF NOT EXISTS idx_conversations_patient ON conversations(patient_id);
CREATE INDEX IF NOT EXISTS idx_health_profiles_patient ON health_profiles(patient_id, id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_chat_rounds_conversation ON chat_rounds(conversation_id, id);
CREATE INDEX IF NOT EXISTS idx_report_interpretations_patient
    ON report_interpretations(patient_id, health_profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments(patient_id, health_profile_id);
CREATE INDEX IF NOT EXISTS idx_consultation_records_doctor ON consultation_records(doctor_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_status ON prescriptions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drug_orders_patient ON drug_orders(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_in_app_messages_patient ON in_app_messages(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_call_logs_conversation ON agent_call_logs(conversation_id, round_id, seq);
CREATE INDEX IF NOT EXISTS idx_agent_call_logs_round ON agent_call_logs(round_id, seq);
CREATE INDEX IF NOT EXISTS idx_med_checkin_patient_profile
    ON med_checkin_records(patient_id, health_profile_id, due_date DESC, status);
CREATE INDEX IF NOT EXISTS idx_med_checkin_prescription ON med_checkin_records(prescription_id);
